contrib: Add git-sync tool
oVirt/vdsm pull request #247
Opened 2022-06-10 23:05 UTC by nirs

The git-sync tool push the current branch to a remote. This is useful
for testing your changes on a host or for running the tests on a test
vm.

Signed-off-by: Nir Soffer <nsoffer@redhat.com>

2022-06-13 19:39 UTC, nirs commented on contrib/git-sync
> +remote_url = urlparse(run(["git", "remote", "get-url", remote]))
Yes, of course I added remote for the host I'm pushing to, this is the way to push
stuff in git.

Here is an example from my local repo:

```
$ git remote -v
host4	nsoffer@host4:src/ovirt-imageio/.git (fetch)
host4	nsoffer@host4:src/ovirt-imageio/.git (push)
```

I will describe the entire flow in the module docstring.

2022-06-13 19:41 UTC, nirs commented on contrib/git-sync
> +run(["ssh", netloc, f"cd {path} && git checkout -b {tmp_branch}"])
It does not have to be the same - the location of the code on the remote is
specified in the git remote.

2022-06-14 06:58 UTC, aesteve-rh commented on contrib/git-sync
> +remote_url = urlparse(run(["git", "remote", "get-url", remote]))
It is a good trick to leverage git to handle your vms as remotes, but yes, this would need to be documented, it is not so obvious.

As a possible alternative, what about use a config file? Since the script has the name of a git plugin, it could have its own configuration in the hidden git folder of the repo, something like `./.git/.gitsync-conf`. For instance, with yaml it could look like:
```yaml
host4: 
  hostname: host4
  path: src/ovirt-imageio
  username: nsoffer
```
And it would be parsed by the python yaml library as a dictionary. And then do:
```python
    with open(config, 'r', encoding='utf-8') as conf_file:
        loaded_conf = yaml.safe_load(conf_file)
    config = loaded_conf[remote]
    netlock = f"{config["username"]}@{config["hostname"]}"
    path = config["path"]
```

2022-06-14 07:01 UTC, aesteve-rh commented on contrib/git-sync
> +run(["ssh", netloc, f"cd {path} && git checkout -b {tmp_branch}"])
True, I read it better with the clarification of the `git remote`. We can resolve this thread.

2022-06-14 07:35 UTC, aesteve-rh commented on contrib/git-sync
> +remote_url = urlparse(run(["git", "remote", "get-url", remote]))
Nevermind the alternative, you push force to the remote directly, so it needs to be kept as a remote.

2022-06-14 16:01 UTC, nirs commented on contrib/git-sync
> +remote_url = urlparse(run(["git", "remote", "get-url", remote]))
The git url is not what you see in ‘git remote -v’ - it return ‘ssh://‘ and parsing it return what we need.

2022-06-20 12:27 UTC, aesteve-rh commented on contrib/git-sync
> +run(["ssh", netloc, f"cd {path} && git checkout {branch} && git branch -D {tmp_branch}"])
Ah right. Changing it to master branch before pushing could also work in this case. As long as this script is tailored for vdsm, if we change master branch name we just need to update the script.

But I like this approach you have right now, which can be copied as is to other repositories without any further consideration. And creating and deleting a branch does not add much overhead.

2022-06-20 12:31 UTC, aesteve-rh requested changes
I have been able to test it, and it works nice, is quite fast too.

I still think it needs some more documentation on how to format the remote url and invoke it. Maybe add a point in the development document, or add a help command line option with a brief syntax and explanation, or both.

Other than that, LGTM :)

2022-06-20 12:32 UTC, aesteve-rh commented on contrib/git-sync
> +remote_url = urlparse(run(["git", "remote", "get-url", remote]))
Right, like that it works fine :)

2022-06-20 19:27 UTC, nirs commented
I will add the missing documentation in the docstring, and we can later show example usage in the development doc.

2022-06-27 07:48 UTC, aesteve-rh commented on contrib/git-sync
> +    git remote add myhost user@myhost:src/vdsm/.git
I think this should be `git remote add myhost ssh://user@myhost:/home/user/src/vdsm/.git`.

2022-06-27 10:54 UTC, nirs commented on contrib/git-sync
> +    git remote add myhost user@myhost:src/vdsm/.git
Right, I see that I have both user@host and ssh://user@host remotes, and git-sync works only with the ssh:// remotes. An older version I had could work with both but it assumed stuff about the remote file system layout.

I will change to use ssh:// urls.

2022-06-27 11:08 UTC, aesteve-rh approved these changes
Thanks! I'm looking forward to having it available in the project (truth be told, I had it already copied in my bin folder).

2022-06-27 11:11 UTC, merged