Cleanup VolumeMonitor API
oVirt/vdsm pull request #64
Opened 2022-02-02 15:07 UTC by nirs

Clean up the API after we moved all the monitoring and extending code
to thinp.VolumeMonitor.

- Remove unneeded optional arguments
- Make methods private
- Move last lefover monitoring code from VM
- Remove duplication
- Avoid unneeded calls to VM methods
- Unify methods names

2022-02-02 15:13 UTC, nirs commented
Tested using live storage migration with all storage domain combinations. This flow
tests snapshot, pre-extend, copy disk, mirror top layer, and finally live merge which does another pre extend.

2022-02-02 15:34 UTC, nirs commented
Marking as draft until #58 is merged.

2022-02-02 17:14 UTC, nirs commented
## Testing extend flow

### In the guest

```
# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda      8:0    0    6G  0 disk 
├─sda1   8:1    0    1M  0 part 
├─sda2   8:2    0    1G  0 part /boot
└─sda3   8:3    0    5G  0 part /
sdb      8:16   0   20G  0 disk 
sr0     11:0    1 1024M  0 rom  
zram0  252:0    0  891M  0 disk [SWAP]

# cat test-extend.sh 
wait=${WAIT:-3}

for i in $(seq 0 39); do
	echo "$(date --rfc-3339=ns) writing block $i at offset $((512*$i)) MiB"
	dd if=/dev/zero bs=1M count=512 seek=$((512*$i)) of=/dev/sdb oflag=direct status=progress
	echo "$(date --rfc-3339=ns) waiting $wait seconds..."
	sleep $wait
done

# sh test-extend.sh 
2022-02-02 19:11:42.164885552+02:00 writing block 0 at offset 0 MiB
406847488 bytes (407 MB, 388 MiB) copied, 1 s, 407 MB/s
512+0 records in
512+0 records out
536870912 bytes (537 MB, 512 MiB) copied, 1.2658 s, 424 MB/s
2022-02-02 19:11:43.434904425+02:00 waiting 3 seconds...
2022-02-02 19:11:46.445929471+02:00 writing block 1 at offset 512 MiB
321912832 bytes (322 MB, 307 MiB) copied, 1 s, 321 MB/s
512+0 records in
512+0 records out
536870912 bytes (537 MB, 512 MiB) copied, 1.49279 s, 360 MB/s
2022-02-02 19:11:47.948412695+02:00 waiting 3 seconds...
2022-02-02 19:11:50.958652537+02:00 writing block 2 at offset 1024 MiB
460324864 bytes (460 MB, 439 MiB) copied, 1 s, 460 MB/s
512+0 records in
512+0 records out
536870912 bytes (537 MB, 512 MiB) copied, 1.15163 s, 466 MB/s
2022-02-02 19:11:52.119829766+02:00 waiting 3 seconds...
2022-02-02 19:11:55.128940126+02:00 writing block 3 at offset 1536 MiB
393216000 bytes (393 MB, 375 MiB) copied, 1 s, 392 MB/s
512+0 records in
512+0 records out
536870912 bytes (537 MB, 512 MiB) copied, 1.37083 s, 392 MB/s
2022-02-02 19:11:56.509524401+02:00 waiting 3 seconds...
2022-02-02 19:11:59.518858682+02:00 writing block 4 at offset 2048 MiB
387973120 bytes (388 MB, 370 MiB) copied, 1 s, 388 MB/s
512+0 records in
512+0 records out
536870912 bytes (537 MB, 512 MiB) copied, 1.28562 s, 418 MB/s
2022-02-02 19:12:00.812952497+02:00 waiting 3 seconds...
...
```

### On the host

```
$ tail -f /var/log/vdsm/vdsm.log | grep extend
2022-02-02 19:11:44,578+0200 INFO  (periodic/0) [vdsm.api] START sendExtendMsg(spUUID='3eb2b49f-dfdd-4807-90b9-4984ade85b3a', volDict={'domainID': 'aecec81f-d464-4a35-9a91-6acf2ca4938c', 'imageID': '904e06fc-8295-4168-b6f3-e409540bdbee', 'internal': False, 'name': 'sdd', 'newSize': 2147483648, 'poolID': '3eb2b49f-dfdd-4807-90b9-4984ade85b3a', 'volumeID': 'f018e2ad-50c5-479f-bcbf-3399b9cb6a18', 'clock': <Clock(total=0.00*, extend-volume=0.00*)>, 'callback': None}, newSize=2147483648, callbackFunc=<bound method VolumeMonitor._extend_volume_completed of <vdsm.virt.thinp.VolumeMonitor object at 0x7f42e8048c88>>) from=internal, task_id=61cac2c6-a66f-46ef-92eb-eba3abfca31c (api:48)
2022-02-02 19:11:45,527+0200 INFO  (mailbox-spm/2) [storage.spm.messages.extend] processRequest: extending volume f018e2ad-50c5-479f-bcbf-3399b9cb6a18 in domain aecec81f-d464-4a35-9a91-6acf2ca4938c (pool 3eb2b49f-dfdd-4807-90b9-4984ade85b3a) to size 2048 (mailbox:168)
2022-02-02 19:11:46,570+0200 INFO  (periodic/3) [vdsm.api] START sendExtendMsg(spUUID='3eb2b49f-dfdd-4807-90b9-4984ade85b3a', volDict={'domainID': 'aecec81f-d464-4a35-9a91-6acf2ca4938c', 'imageID': '904e06fc-8295-4168-b6f3-e409540bdbee', 'internal': False, 'name': 'sdd', 'newSize': 2147483648, 'poolID': '3eb2b49f-dfdd-4807-90b9-4984ade85b3a', 'volumeID': 'f018e2ad-50c5-479f-bcbf-3399b9cb6a18', 'clock': <Clock(total=0.00*, extend-volume=0.00*)>, 'callback': None}, newSize=2147483648, callbackFunc=<bound method VolumeMonitor._extend_volume_completed of <vdsm.virt.thinp.VolumeMonitor object at 0x7f42e8048c88>>) from=internal, task_id=1a810a44-f192-4af5-91a5-762a5b24c7a2 (api:48)
2022-02-02 19:11:46,708+0200 INFO  (mailbox-hsm/1) [storage.threadpool.workerthread] START task 719de81c-4550-4851-bbf6-b43ae8dd7f3c (cmd=<function runTask at 0x7f432efec9d8>, args=(<bound method VolumeMonitor._extend_volume_completed of <vdsm.virt.thinp.VolumeMonitor object at 0x7f42e8048c88>>, {'domainID': 'aecec81f-d464-4a35-9a91-6acf2ca4938c', 'imageID': '904e06fc-8295-4168-b6f3-e409540bdbee', 'internal': False, 'name': 'sdd', 'newSize': 2147483648, 'poolID': '3eb2b49f-dfdd-4807-90b9-4984ade85b3a', 'volumeID': 'f018e2ad-50c5-479f-bcbf-3399b9cb6a18', 'clock': <Clock(total=2.13*, extend-volume=2.13, refresh-volume=0.00*)>, 'callback': None})) (threadPool:146)
2022-02-02 19:11:46,896+0200 INFO  (mailbox-hsm/1) [virt.vm] (vmId='268a3a08-c38b-4b47-9215-42ef05babd62') Extend volume f018e2ad-50c5-479f-bcbf-3399b9cb6a18 completed <Clock(total=2.32, extend-volume=2.13, refresh-volume=0.19)> (thinp:552)
2022-02-02 19:11:52,581+0200 INFO  (periodic/3) [vdsm.api] START sendExtendMsg(spUUID='3eb2b49f-dfdd-4807-90b9-4984ade85b3a', volDict={'domainID': 'aecec81f-d464-4a35-9a91-6acf2ca4938c', 'imageID': '904e06fc-8295-4168-b6f3-e409540bdbee', 'internal': False, 'name': 'sdd', 'newSize': 3221225472, 'poolID': '3eb2b49f-dfdd-4807-90b9-4984ade85b3a', 'volumeID': 'f018e2ad-50c5-479f-bcbf-3399b9cb6a18', 'clock': <Clock(total=0.00*, extend-volume=0.00*)>, 'callback': None}, newSize=3221225472, callbackFunc=<bound method VolumeMonitor._extend_volume_completed of <vdsm.virt.thinp.VolumeMonitor object at 0x7f42e8048c88>>) from=internal, task_id=1ed5edfb-815a-474d-a66a-d41aa03b68c2 (api:48)
2022-02-02 19:11:53,639+0200 INFO  (mailbox-spm/1) [storage.spm.messages.extend] processRequest: extending volume f018e2ad-50c5-479f-bcbf-3399b9cb6a18 in domain aecec81f-d464-4a35-9a91-6acf2ca4938c (pool 3eb2b49f-dfdd-4807-90b9-4984ade85b3a) to size 3072 (mailbox:168)
2022-02-02 19:11:54,598+0200 INFO  (periodic/0) [vdsm.api] START sendExtendMsg(spUUID='3eb2b49f-dfdd-4807-90b9-4984ade85b3a', volDict={'domainID': 'aecec81f-d464-4a35-9a91-6acf2ca4938c', 'imageID': '904e06fc-8295-4168-b6f3-e409540bdbee', 'internal': False, 'name': 'sdd', 'newSize': 3221225472, 'poolID': '3eb2b49f-dfdd-4807-90b9-4984ade85b3a', 'volumeID': 'f018e2ad-50c5-479f-bcbf-3399b9cb6a18', 'clock': <Clock(total=0.00*, extend-volume=0.00*)>, 'callback': None}, newSize=3221225472, callbackFunc=<bound method VolumeMonitor._extend_volume_completed of <vdsm.virt.thinp.VolumeMonitor object at 0x7f42e8048c88>>) from=internal, task_id=356e77b7-d866-4d82-a416-d32938c7f988 (api:48)
2022-02-02 19:11:54,702+0200 INFO  (mailbox-hsm/0) [storage.threadpool.workerthread] START task bdd485f2-0fc9-4e76-9a38-5d1d28a433e5 (cmd=<function runTask at 0x7f432efec9d8>, args=(<bound method VolumeMonitor._extend_volume_completed of <vdsm.virt.thinp.VolumeMonitor object at 0x7f42e8048c88>>, {'domainID': 'aecec81f-d464-4a35-9a91-6acf2ca4938c', 'imageID': '904e06fc-8295-4168-b6f3-e409540bdbee', 'internal': False, 'name': 'sdd', 'newSize': 3221225472, 'poolID': '3eb2b49f-dfdd-4807-90b9-4984ade85b3a', 'volumeID': 'f018e2ad-50c5-479f-bcbf-3399b9cb6a18', 'clock': <Clock(total=2.12*, extend-volume=2.12, refresh-volume=0.00*)>, 'callback': None})) (threadPool:146)
2022-02-02 19:11:54,873+0200 INFO  (mailbox-hsm/0) [virt.vm] (vmId='268a3a08-c38b-4b47-9215-42ef05babd62') Extend volume f018e2ad-50c5-479f-bcbf-3399b9cb6a18 completed <Clock(total=2.29, extend-volume=2.12, refresh-volume=0.17)> (thinp:552)
...
```

2022-02-02 17:18 UTC, nirs commented
/ost

2022-02-03 09:57 UTC, vjuranek requested changes
Only few typos, otherwise LGTM

2022-02-03 09:57 UTC, vjuranek commented on lib/vdsm/virt/thinp.py
> +        The drive must be part of the backing chain. This does not work volumes
"does not work volumes" -> "does not work for volumes"

2022-02-03 09:57 UTC, vjuranek commented on lib/vdsm/virt/thinp.py
>                  drive.name)
"to support working" probably should be "to support work"

2022-02-03 09:57 UTC, vjuranek commented on lib/vdsm/virt/thinp.py
> +    # Manging libvirt block threshold.
"Manging" -> "Managing"

2022-02-03 17:28 UTC, nirs commented
@vjuranek new address your comments and add new commit fixing spelling in existing code. No code change so this is still verified.

2022-02-03 17:38 UTC, nirs commented
/ost

2022-02-07 11:32 UTC, vjuranek approved these changes

2022-02-07 11:32 UTC, merged