vdsm-tool: Create libvirtd conf file for el9
oVirt/vdsm pull request #75
Opened 2022-02-14 08:06 UTC by hbraha

In el9, we use the monolithic daemon libvirtd,
so we need to create a libvirtd config manually
since it's not shipped by deafult.

2022-02-14 10:32 UTC, tinez requested changes

2022-02-14 10:32 UTC, tinez commented on lib/vdsm/tool/configurators/libvirt.py
> +_LIBVIRT_CONF_PATH = "/etc/sysconfig/libvirtd"
We already have that path defined under the `LDCONF` key (line ~360) in a better way - it uses the `constants` module. Let's move that definition here, and reuse the new variable in `LDCONF`

2022-02-14 10:32 UTC, tinez commented on lib/vdsm/tool/configurators/libvirt.py
> +    # Creates libvirt conf file if not exists
Strictly speaking, this is not really "libvirt configration" - this one can be found in `/etc/libvirt/libvirt.conf`. Let's call it "system-level libvirt config". This applies to the commit message too.

2022-02-16 11:14 UTC, tinez approved these changes

2022-02-16 11:17 UTC, tinez commented
/ost

2022-02-16 11:18 UTC, almusil approved these changes

2022-02-16 11:51 UTC, tinez commented
/ost

2022-02-17 09:36 UTC, merged